# Generated by Django 5.0.2 on 2024-02-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
