# Generated by Django 4.2.10 on 2024-02-29 10:40

from django.conf import (
    settings,
)
from django.db import (
    migrations,
    models,
)
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "account",
            "0002_initial",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountmodel",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
