# Generated by Django 5.0.2 on 2024-02-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_usermodel_is_active_usermodel_is_staff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="usermodel",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="usermodel",
            name="is_superuser",
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
