# Generated by Django 5.0.2 on 2024-02-25 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_accountmodel_updated_at"),
        (
            "authentication",
            "0004_remove_usermodel_is_active_remove_usermodel_is_staff_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="account_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="account.accountmodel",
            ),
        ),
    ]
