# Generated by Django 5.0.2 on 2024-02-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_usermodel_account_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="account_model",
        ),
    ]
